# Generated by Django 2.2.3 on 2019-09-03 18:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(blank=True, help_text='Inserisci il più alto titolo di studio ottenuto', max_length=30, verbose_name='Titolo di studio')),
                ('image', models.FileField(blank=True, help_text="Si consiglia fortemente l'uso di immagini di dimensioni 400x400 px", upload_to='profile', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'], 'Formato non valido. Inserisci una immagine con uno dei seguenti formati: jpg,jpeg,png')], verbose_name='Immagine di profilo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
