# Generated by Django 2.2.3 on 2019-09-03 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(blank=True, to='catalog.Item')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='Proprietario')),
            ],
        ),
    ]
