# Generated by Django 2.2.3 on 2019-09-03 18:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.TextField(max_length=1000, verbose_name="Descrizione dell'oggetto")),
                ('subject', models.CharField(max_length=30, verbose_name='Materia/disciplina')),
                ('school_level', models.CharField(choices=[('M', 'Medie'), ('S', 'Superiori'), ('U', 'Università')], max_length=1, verbose_name='Livello scolastico')),
                ('is_visible', models.BooleanField(default=True)),
                ('vote', models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0, 'Il voto minimo non può essere minore di 0'), django.core.validators.MaxValueValidator(5, 'Il voto massimo non può essere più di 5')], verbose_name='Voto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(2, 'Il prezzo minimo non può essere minore di 2€')], verbose_name='Prezzo di vendita')),
                ('image', models.FileField(help_text="Si consiglia fortemente l'uso di immagini di dimensioni 400x400 px", upload_to='item/preview', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'], 'Formato non valido. Inserisci una immagine con uno dei seguenti formati: jpg,jpeg,png')], verbose_name='Immagine')),
                ('file', models.FileField(help_text="E' obbligatorio l'uso del formato pdf.", upload_to='item/files', validators=[django.core.validators.FileExtensionValidator(['pdf'], 'Formato non valido. Inserisci un file in formato pdf')])),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Profile', verbose_name='Venditore')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewsObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('reviewed_object', models.ManyToManyField(blank=True, to='catalog.Item')),
            ],
        ),
        migrations.CreateModel(
            name='HaveItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemspurchased', models.ManyToManyField(blank=True, to='catalog.Item')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
    ]
