# Generated by Django 2.2.3 on 2019-09-03 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(help_text="Si consiglia fortemente l'uso di immagini di dimensioni 400x400 px", upload_to='item/preview', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'], 'Formato non valido. Inserisci una immagine con uno dei seguenti formati: jpg,jpeg,png')], verbose_name='Immagine di anteprima'),
        ),
    ]
